//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan", IsNullable = false)]
public partial class ShowPlanXML
{

    private ShowPlanXMLBatchSequence batchSequenceField;

    private decimal versionField;

    private string buildField;

    /// <remarks/>
    public ShowPlanXMLBatchSequence BatchSequence
    {
        get
        {
            return this.batchSequenceField;
        }
        set
        {
            this.batchSequenceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Build
    {
        get
        {
            return this.buildField;
        }
        set
        {
            this.buildField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequence
{

    private ShowPlanXMLBatchSequenceBatch batchField;

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatch Batch
    {
        get
        {
            return this.batchField;
        }
        set
        {
            this.batchField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatch
{

    private ShowPlanXMLBatchSequenceBatchStmtSimple[] statementsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("StmtSimple", IsNullable = false)]
    public ShowPlanXMLBatchSequenceBatchStmtSimple[] Statements
    {
        get
        {
            return this.statementsField;
        }
        set
        {
            this.statementsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimple
{

    private ShowPlanXMLBatchSequenceBatchStmtSimpleStatementSetOptions statementSetOptionsField;

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlan queryPlanField;

    private string statementTextField;

    private byte statementIdField;

    private byte statementCompIdField;

    private string statementTypeField;

    private bool retrievedFromCacheField;

    private decimal statementSubTreeCostField;

    private bool statementSubTreeCostFieldSpecified;

    private byte statementEstRowsField;

    private bool statementEstRowsFieldSpecified;

    private bool securityPolicyAppliedField;

    private bool securityPolicyAppliedFieldSpecified;

    private string statementOptmLevelField;

    private string queryHashField;

    private string queryPlanHashField;

    private byte cardinalityEstimationModelVersionField;

    private bool cardinalityEstimationModelVersionFieldSpecified;

    private string parameterizedTextField;

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleStatementSetOptions StatementSetOptions
    {
        get
        {
            return this.statementSetOptionsField;
        }
        set
        {
            this.statementSetOptionsField = value;
        }
    }

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlan QueryPlan
    {
        get
        {
            return this.queryPlanField;
        }
        set
        {
            this.queryPlanField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string StatementText
    {
        get
        {
            return this.statementTextField;
        }
        set
        {
            this.statementTextField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte StatementId
    {
        get
        {
            return this.statementIdField;
        }
        set
        {
            this.statementIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte StatementCompId
    {
        get
        {
            return this.statementCompIdField;
        }
        set
        {
            this.statementCompIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string StatementType
    {
        get
        {
            return this.statementTypeField;
        }
        set
        {
            this.statementTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool RetrievedFromCache
    {
        get
        {
            return this.retrievedFromCacheField;
        }
        set
        {
            this.retrievedFromCacheField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal StatementSubTreeCost
    {
        get
        {
            return this.statementSubTreeCostField;
        }
        set
        {
            this.statementSubTreeCostField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StatementSubTreeCostSpecified
    {
        get
        {
            return this.statementSubTreeCostFieldSpecified;
        }
        set
        {
            this.statementSubTreeCostFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte StatementEstRows
    {
        get
        {
            return this.statementEstRowsField;
        }
        set
        {
            this.statementEstRowsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StatementEstRowsSpecified
    {
        get
        {
            return this.statementEstRowsFieldSpecified;
        }
        set
        {
            this.statementEstRowsFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool SecurityPolicyApplied
    {
        get
        {
            return this.securityPolicyAppliedField;
        }
        set
        {
            this.securityPolicyAppliedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SecurityPolicyAppliedSpecified
    {
        get
        {
            return this.securityPolicyAppliedFieldSpecified;
        }
        set
        {
            this.securityPolicyAppliedFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string StatementOptmLevel
    {
        get
        {
            return this.statementOptmLevelField;
        }
        set
        {
            this.statementOptmLevelField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string QueryHash
    {
        get
        {
            return this.queryHashField;
        }
        set
        {
            this.queryHashField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string QueryPlanHash
    {
        get
        {
            return this.queryPlanHashField;
        }
        set
        {
            this.queryPlanHashField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte CardinalityEstimationModelVersion
    {
        get
        {
            return this.cardinalityEstimationModelVersionField;
        }
        set
        {
            this.cardinalityEstimationModelVersionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CardinalityEstimationModelVersionSpecified
    {
        get
        {
            return this.cardinalityEstimationModelVersionFieldSpecified;
        }
        set
        {
            this.cardinalityEstimationModelVersionFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ParameterizedText
    {
        get
        {
            return this.parameterizedTextField;
        }
        set
        {
            this.parameterizedTextField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleStatementSetOptions
{

    private bool qUOTED_IDENTIFIERField;

    private bool aRITHABORTField;

    private bool cONCAT_NULL_YIELDS_NULLField;

    private bool aNSI_NULLSField;

    private bool aNSI_PADDINGField;

    private bool aNSI_WARNINGSField;

    private bool nUMERIC_ROUNDABORTField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool QUOTED_IDENTIFIER
    {
        get
        {
            return this.qUOTED_IDENTIFIERField;
        }
        set
        {
            this.qUOTED_IDENTIFIERField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool ARITHABORT
    {
        get
        {
            return this.aRITHABORTField;
        }
        set
        {
            this.aRITHABORTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool CONCAT_NULL_YIELDS_NULL
    {
        get
        {
            return this.cONCAT_NULL_YIELDS_NULLField;
        }
        set
        {
            this.cONCAT_NULL_YIELDS_NULLField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool ANSI_NULLS
    {
        get
        {
            return this.aNSI_NULLSField;
        }
        set
        {
            this.aNSI_NULLSField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool ANSI_PADDING
    {
        get
        {
            return this.aNSI_PADDINGField;
        }
        set
        {
            this.aNSI_PADDINGField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool ANSI_WARNINGS
    {
        get
        {
            return this.aNSI_WARNINGSField;
        }
        set
        {
            this.aNSI_WARNINGSField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool NUMERIC_ROUNDABORT
    {
        get
        {
            return this.nUMERIC_ROUNDABORTField;
        }
        set
        {
            this.nUMERIC_ROUNDABORTField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlan
{

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanMemoryGrantInfo memoryGrantInfoField;

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanOptimizerHardwareDependentProperties optimizerHardwareDependentPropertiesField;

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanTraceFlags traceFlagsField;

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOp relOpField;

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanParameterList parameterListField;

    private string nonParallelPlanReasonField;

    private byte cachedPlanSizeField;

    private byte compileTimeField;

    private byte compileCPUField;

    private byte compileMemoryField;

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanMemoryGrantInfo MemoryGrantInfo
    {
        get
        {
            return this.memoryGrantInfoField;
        }
        set
        {
            this.memoryGrantInfoField = value;
        }
    }

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanOptimizerHardwareDependentProperties OptimizerHardwareDependentProperties
    {
        get
        {
            return this.optimizerHardwareDependentPropertiesField;
        }
        set
        {
            this.optimizerHardwareDependentPropertiesField = value;
        }
    }

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanTraceFlags TraceFlags
    {
        get
        {
            return this.traceFlagsField;
        }
        set
        {
            this.traceFlagsField = value;
        }
    }

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOp RelOp
    {
        get
        {
            return this.relOpField;
        }
        set
        {
            this.relOpField = value;
        }
    }

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanParameterList ParameterList
    {
        get
        {
            return this.parameterListField;
        }
        set
        {
            this.parameterListField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NonParallelPlanReason
    {
        get
        {
            return this.nonParallelPlanReasonField;
        }
        set
        {
            this.nonParallelPlanReasonField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte CachedPlanSize
    {
        get
        {
            return this.cachedPlanSizeField;
        }
        set
        {
            this.cachedPlanSizeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte CompileTime
    {
        get
        {
            return this.compileTimeField;
        }
        set
        {
            this.compileTimeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte CompileCPU
    {
        get
        {
            return this.compileCPUField;
        }
        set
        {
            this.compileCPUField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte CompileMemory
    {
        get
        {
            return this.compileMemoryField;
        }
        set
        {
            this.compileMemoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanMemoryGrantInfo
{

    private byte serialRequiredMemoryField;

    private byte serialDesiredMemoryField;

    private byte grantedMemoryField;

    private byte maxUsedMemoryField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte SerialRequiredMemory
    {
        get
        {
            return this.serialRequiredMemoryField;
        }
        set
        {
            this.serialRequiredMemoryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte SerialDesiredMemory
    {
        get
        {
            return this.serialDesiredMemoryField;
        }
        set
        {
            this.serialDesiredMemoryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte GrantedMemory
    {
        get
        {
            return this.grantedMemoryField;
        }
        set
        {
            this.grantedMemoryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte MaxUsedMemory
    {
        get
        {
            return this.maxUsedMemoryField;
        }
        set
        {
            this.maxUsedMemoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanOptimizerHardwareDependentProperties
{

    private uint estimatedAvailableMemoryGrantField;

    private uint estimatedPagesCachedField;

    private byte estimatedAvailableDegreeOfParallelismField;

    private uint maxCompileMemoryField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint EstimatedAvailableMemoryGrant
    {
        get
        {
            return this.estimatedAvailableMemoryGrantField;
        }
        set
        {
            this.estimatedAvailableMemoryGrantField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint EstimatedPagesCached
    {
        get
        {
            return this.estimatedPagesCachedField;
        }
        set
        {
            this.estimatedPagesCachedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte EstimatedAvailableDegreeOfParallelism
    {
        get
        {
            return this.estimatedAvailableDegreeOfParallelismField;
        }
        set
        {
            this.estimatedAvailableDegreeOfParallelismField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint MaxCompileMemory
    {
        get
        {
            return this.maxCompileMemoryField;
        }
        set
        {
            this.maxCompileMemoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanTraceFlags
{

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanTraceFlagsTraceFlag traceFlagField;

    private byte isCompileTimeField;

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanTraceFlagsTraceFlag TraceFlag
    {
        get
        {
            return this.traceFlagField;
        }
        set
        {
            this.traceFlagField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte IsCompileTime
    {
        get
        {
            return this.isCompileTimeField;
        }
        set
        {
            this.isCompileTimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanTraceFlagsTraceFlag
{

    private ushort valueField;

    private string scopeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Scope
    {
        get
        {
            return this.scopeField;
        }
        set
        {
            this.scopeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOp
{

    private object outputListField;

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdate updateField;

    private byte nodeIdField;

    private string physicalOpField;

    private string logicalOpField;

    private byte estimateRowsField;

    private decimal estimateIOField;

    private float estimateCPUField;

    private byte avgRowSizeField;

    private decimal estimatedTotalSubtreeCostField;

    private byte parallelField;

    private byte estimateRebindsField;

    private byte estimateRewindsField;

    private string estimatedExecutionModeField;

    /// <remarks/>
    public object OutputList
    {
        get
        {
            return this.outputListField;
        }
        set
        {
            this.outputListField = value;
        }
    }

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdate Update
    {
        get
        {
            return this.updateField;
        }
        set
        {
            this.updateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte NodeId
    {
        get
        {
            return this.nodeIdField;
        }
        set
        {
            this.nodeIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PhysicalOp
    {
        get
        {
            return this.physicalOpField;
        }
        set
        {
            this.physicalOpField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LogicalOp
    {
        get
        {
            return this.logicalOpField;
        }
        set
        {
            this.logicalOpField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte EstimateRows
    {
        get
        {
            return this.estimateRowsField;
        }
        set
        {
            this.estimateRowsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal EstimateIO
    {
        get
        {
            return this.estimateIOField;
        }
        set
        {
            this.estimateIOField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float EstimateCPU
    {
        get
        {
            return this.estimateCPUField;
        }
        set
        {
            this.estimateCPUField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte AvgRowSize
    {
        get
        {
            return this.avgRowSizeField;
        }
        set
        {
            this.avgRowSizeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal EstimatedTotalSubtreeCost
    {
        get
        {
            return this.estimatedTotalSubtreeCostField;
        }
        set
        {
            this.estimatedTotalSubtreeCostField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte Parallel
    {
        get
        {
            return this.parallelField;
        }
        set
        {
            this.parallelField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte EstimateRebinds
    {
        get
        {
            return this.estimateRebindsField;
        }
        set
        {
            this.estimateRebindsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte EstimateRewinds
    {
        get
        {
            return this.estimateRewindsField;
        }
        set
        {
            this.estimateRewindsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EstimatedExecutionMode
    {
        get
        {
            return this.estimatedExecutionModeField;
        }
        set
        {
            this.estimatedExecutionModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdate
{

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateObject objectField;

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateSetPredicate setPredicateField;

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOp relOpField;

    private byte dMLRequestSortField;

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateObject Object
    {
        get
        {
            return this.objectField;
        }
        set
        {
            this.objectField = value;
        }
    }

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateSetPredicate SetPredicate
    {
        get
        {
            return this.setPredicateField;
        }
        set
        {
            this.setPredicateField = value;
        }
    }

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOp RelOp
    {
        get
        {
            return this.relOpField;
        }
        set
        {
            this.relOpField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte DMLRequestSort
    {
        get
        {
            return this.dMLRequestSortField;
        }
        set
        {
            this.dMLRequestSortField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateObject
{

    private string databaseField;

    private string schemaField;

    private string tableField;

    private string indexField;

    private string indexKindField;

    private string storageField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Database
    {
        get
        {
            return this.databaseField;
        }
        set
        {
            this.databaseField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Schema
    {
        get
        {
            return this.schemaField;
        }
        set
        {
            this.schemaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Table
    {
        get
        {
            return this.tableField;
        }
        set
        {
            this.tableField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Index
    {
        get
        {
            return this.indexField;
        }
        set
        {
            this.indexField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string IndexKind
    {
        get
        {
            return this.indexKindField;
        }
        set
        {
            this.indexKindField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Storage
    {
        get
        {
            return this.storageField;
        }
        set
        {
            this.storageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateSetPredicate
{

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateSetPredicateScalarOperator scalarOperatorField;

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateSetPredicateScalarOperator ScalarOperator
    {
        get
        {
            return this.scalarOperatorField;
        }
        set
        {
            this.scalarOperatorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateSetPredicateScalarOperator
{

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateSetPredicateScalarOperatorScalarExpressionList scalarExpressionListField;

    private string scalarStringField;

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateSetPredicateScalarOperatorScalarExpressionList ScalarExpressionList
    {
        get
        {
            return this.scalarExpressionListField;
        }
        set
        {
            this.scalarExpressionListField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ScalarString
    {
        get
        {
            return this.scalarStringField;
        }
        set
        {
            this.scalarStringField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateSetPredicateScalarOperatorScalarExpressionList
{

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateSetPredicateScalarOperatorScalarExpressionListScalarOperator scalarOperatorField;

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateSetPredicateScalarOperatorScalarExpressionListScalarOperator ScalarOperator
    {
        get
        {
            return this.scalarOperatorField;
        }
        set
        {
            this.scalarOperatorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateSetPredicateScalarOperatorScalarExpressionListScalarOperator
{

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateSetPredicateScalarOperatorScalarExpressionListScalarOperatorAssign[] multipleAssignField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Assign", IsNullable = false)]
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateSetPredicateScalarOperatorScalarExpressionListScalarOperatorAssign[] MultipleAssign
    {
        get
        {
            return this.multipleAssignField;
        }
        set
        {
            this.multipleAssignField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateSetPredicateScalarOperatorScalarExpressionListScalarOperatorAssign
{

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateSetPredicateScalarOperatorScalarExpressionListScalarOperatorAssignColumnReference columnReferenceField;

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateSetPredicateScalarOperatorScalarExpressionListScalarOperatorAssignScalarOperator scalarOperatorField;

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateSetPredicateScalarOperatorScalarExpressionListScalarOperatorAssignColumnReference ColumnReference
    {
        get
        {
            return this.columnReferenceField;
        }
        set
        {
            this.columnReferenceField = value;
        }
    }

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateSetPredicateScalarOperatorScalarExpressionListScalarOperatorAssignScalarOperator ScalarOperator
    {
        get
        {
            return this.scalarOperatorField;
        }
        set
        {
            this.scalarOperatorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateSetPredicateScalarOperatorScalarExpressionListScalarOperatorAssignColumnReference
{

    private string databaseField;

    private string schemaField;

    private string tableField;

    private string columnField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Database
    {
        get
        {
            return this.databaseField;
        }
        set
        {
            this.databaseField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Schema
    {
        get
        {
            return this.schemaField;
        }
        set
        {
            this.schemaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Table
    {
        get
        {
            return this.tableField;
        }
        set
        {
            this.tableField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Column
    {
        get
        {
            return this.columnField;
        }
        set
        {
            this.columnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateSetPredicateScalarOperatorScalarExpressionListScalarOperatorAssignScalarOperator
{

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateSetPredicateScalarOperatorScalarExpressionListScalarOperatorAssignScalarOperatorIdentifier identifierField;

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateSetPredicateScalarOperatorScalarExpressionListScalarOperatorAssignScalarOperatorIdentifier Identifier
    {
        get
        {
            return this.identifierField;
        }
        set
        {
            this.identifierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateSetPredicateScalarOperatorScalarExpressionListScalarOperatorAssignScalarOperatorIdentifier
{

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateSetPredicateScalarOperatorScalarExpressionListScalarOperatorAssignScalarOperatorIdentifierColumnReference columnReferenceField;

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateSetPredicateScalarOperatorScalarExpressionListScalarOperatorAssignScalarOperatorIdentifierColumnReference ColumnReference
    {
        get
        {
            return this.columnReferenceField;
        }
        set
        {
            this.columnReferenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateSetPredicateScalarOperatorScalarExpressionListScalarOperatorAssignScalarOperatorIdentifierColumnReference
{

    private string columnField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Column
    {
        get
        {
            return this.columnField;
        }
        set
        {
            this.columnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOp
{

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpColumnReference[] outputListField;

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalar computeScalarField;

    private byte nodeIdField;

    private string physicalOpField;

    private string logicalOpField;

    private byte estimateRowsField;

    private byte estimateIOField;

    private float estimateCPUField;

    private ushort avgRowSizeField;

    private float estimatedTotalSubtreeCostField;

    private byte parallelField;

    private byte estimateRebindsField;

    private byte estimateRewindsField;

    private string estimatedExecutionModeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ColumnReference", IsNullable = false)]
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpColumnReference[] OutputList
    {
        get
        {
            return this.outputListField;
        }
        set
        {
            this.outputListField = value;
        }
    }

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalar ComputeScalar
    {
        get
        {
            return this.computeScalarField;
        }
        set
        {
            this.computeScalarField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte NodeId
    {
        get
        {
            return this.nodeIdField;
        }
        set
        {
            this.nodeIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PhysicalOp
    {
        get
        {
            return this.physicalOpField;
        }
        set
        {
            this.physicalOpField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LogicalOp
    {
        get
        {
            return this.logicalOpField;
        }
        set
        {
            this.logicalOpField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte EstimateRows
    {
        get
        {
            return this.estimateRowsField;
        }
        set
        {
            this.estimateRowsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte EstimateIO
    {
        get
        {
            return this.estimateIOField;
        }
        set
        {
            this.estimateIOField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float EstimateCPU
    {
        get
        {
            return this.estimateCPUField;
        }
        set
        {
            this.estimateCPUField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort AvgRowSize
    {
        get
        {
            return this.avgRowSizeField;
        }
        set
        {
            this.avgRowSizeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float EstimatedTotalSubtreeCost
    {
        get
        {
            return this.estimatedTotalSubtreeCostField;
        }
        set
        {
            this.estimatedTotalSubtreeCostField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte Parallel
    {
        get
        {
            return this.parallelField;
        }
        set
        {
            this.parallelField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte EstimateRebinds
    {
        get
        {
            return this.estimateRebindsField;
        }
        set
        {
            this.estimateRebindsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte EstimateRewinds
    {
        get
        {
            return this.estimateRewindsField;
        }
        set
        {
            this.estimateRewindsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EstimatedExecutionMode
    {
        get
        {
            return this.estimatedExecutionModeField;
        }
        set
        {
            this.estimatedExecutionModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpColumnReference
{

    private string columnField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Column
    {
        get
        {
            return this.columnField;
        }
        set
        {
            this.columnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalar
{

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarDefinedValues definedValuesField;

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOp relOpField;

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarDefinedValues DefinedValues
    {
        get
        {
            return this.definedValuesField;
        }
        set
        {
            this.definedValuesField = value;
        }
    }

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOp RelOp
    {
        get
        {
            return this.relOpField;
        }
        set
        {
            this.relOpField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarDefinedValues
{

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarDefinedValuesDefinedValue definedValueField;

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarDefinedValuesDefinedValue DefinedValue
    {
        get
        {
            return this.definedValueField;
        }
        set
        {
            this.definedValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarDefinedValuesDefinedValue
{

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarDefinedValuesDefinedValueColumnReference columnReferenceField;

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarDefinedValuesDefinedValueScalarOperator scalarOperatorField;

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarDefinedValuesDefinedValueColumnReference ColumnReference
    {
        get
        {
            return this.columnReferenceField;
        }
        set
        {
            this.columnReferenceField = value;
        }
    }

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarDefinedValuesDefinedValueScalarOperator ScalarOperator
    {
        get
        {
            return this.scalarOperatorField;
        }
        set
        {
            this.scalarOperatorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarDefinedValuesDefinedValueColumnReference
{

    private string columnField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Column
    {
        get
        {
            return this.columnField;
        }
        set
        {
            this.columnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarDefinedValuesDefinedValueScalarOperator
{

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarDefinedValuesDefinedValueScalarOperatorConvert convertField;

    private string scalarStringField;

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarDefinedValuesDefinedValueScalarOperatorConvert Convert
    {
        get
        {
            return this.convertField;
        }
        set
        {
            this.convertField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ScalarString
    {
        get
        {
            return this.scalarStringField;
        }
        set
        {
            this.scalarStringField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarDefinedValuesDefinedValueScalarOperatorConvert
{

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarDefinedValuesDefinedValueScalarOperatorConvertScalarOperator scalarOperatorField;

    private string dataTypeField;

    private uint lengthField;

    private byte styleField;

    private byte implicitField;

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarDefinedValuesDefinedValueScalarOperatorConvertScalarOperator ScalarOperator
    {
        get
        {
            return this.scalarOperatorField;
        }
        set
        {
            this.scalarOperatorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DataType
    {
        get
        {
            return this.dataTypeField;
        }
        set
        {
            this.dataTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint Length
    {
        get
        {
            return this.lengthField;
        }
        set
        {
            this.lengthField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte Style
    {
        get
        {
            return this.styleField;
        }
        set
        {
            this.styleField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte Implicit
    {
        get
        {
            return this.implicitField;
        }
        set
        {
            this.implicitField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarDefinedValuesDefinedValueScalarOperatorConvertScalarOperator
{

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarDefinedValuesDefinedValueScalarOperatorConvertScalarOperatorIdentifier identifierField;

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarDefinedValuesDefinedValueScalarOperatorConvertScalarOperatorIdentifier Identifier
    {
        get
        {
            return this.identifierField;
        }
        set
        {
            this.identifierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarDefinedValuesDefinedValueScalarOperatorConvertScalarOperatorIdentifier
{

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarDefinedValuesDefinedValueScalarOperatorConvertScalarOperatorIdentifierColumnReference columnReferenceField;

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarDefinedValuesDefinedValueScalarOperatorConvertScalarOperatorIdentifierColumnReference ColumnReference
    {
        get
        {
            return this.columnReferenceField;
        }
        set
        {
            this.columnReferenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarDefinedValuesDefinedValueScalarOperatorConvertScalarOperatorIdentifierColumnReference
{

    private string columnField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Column
    {
        get
        {
            return this.columnField;
        }
        set
        {
            this.columnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOp
{

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpOutputList outputListField;

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpComputeScalar computeScalarField;

    private byte nodeIdField;

    private string physicalOpField;

    private string logicalOpField;

    private byte estimateRowsField;

    private byte estimateIOField;

    private float estimateCPUField;

    private byte avgRowSizeField;

    private float estimatedTotalSubtreeCostField;

    private byte parallelField;

    private byte estimateRebindsField;

    private byte estimateRewindsField;

    private string estimatedExecutionModeField;

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpOutputList OutputList
    {
        get
        {
            return this.outputListField;
        }
        set
        {
            this.outputListField = value;
        }
    }

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpComputeScalar ComputeScalar
    {
        get
        {
            return this.computeScalarField;
        }
        set
        {
            this.computeScalarField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte NodeId
    {
        get
        {
            return this.nodeIdField;
        }
        set
        {
            this.nodeIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PhysicalOp
    {
        get
        {
            return this.physicalOpField;
        }
        set
        {
            this.physicalOpField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LogicalOp
    {
        get
        {
            return this.logicalOpField;
        }
        set
        {
            this.logicalOpField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte EstimateRows
    {
        get
        {
            return this.estimateRowsField;
        }
        set
        {
            this.estimateRowsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte EstimateIO
    {
        get
        {
            return this.estimateIOField;
        }
        set
        {
            this.estimateIOField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float EstimateCPU
    {
        get
        {
            return this.estimateCPUField;
        }
        set
        {
            this.estimateCPUField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte AvgRowSize
    {
        get
        {
            return this.avgRowSizeField;
        }
        set
        {
            this.avgRowSizeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float EstimatedTotalSubtreeCost
    {
        get
        {
            return this.estimatedTotalSubtreeCostField;
        }
        set
        {
            this.estimatedTotalSubtreeCostField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte Parallel
    {
        get
        {
            return this.parallelField;
        }
        set
        {
            this.parallelField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte EstimateRebinds
    {
        get
        {
            return this.estimateRebindsField;
        }
        set
        {
            this.estimateRebindsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte EstimateRewinds
    {
        get
        {
            return this.estimateRewindsField;
        }
        set
        {
            this.estimateRewindsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EstimatedExecutionMode
    {
        get
        {
            return this.estimatedExecutionModeField;
        }
        set
        {
            this.estimatedExecutionModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpOutputList
{

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpOutputListColumnReference columnReferenceField;

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpOutputListColumnReference ColumnReference
    {
        get
        {
            return this.columnReferenceField;
        }
        set
        {
            this.columnReferenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpOutputListColumnReference
{

    private string columnField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Column
    {
        get
        {
            return this.columnField;
        }
        set
        {
            this.columnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpComputeScalar
{

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpComputeScalarDefinedValues definedValuesField;

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpComputeScalarRelOp relOpField;

    private byte computeSequenceField;

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpComputeScalarDefinedValues DefinedValues
    {
        get
        {
            return this.definedValuesField;
        }
        set
        {
            this.definedValuesField = value;
        }
    }

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpComputeScalarRelOp RelOp
    {
        get
        {
            return this.relOpField;
        }
        set
        {
            this.relOpField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte ComputeSequence
    {
        get
        {
            return this.computeSequenceField;
        }
        set
        {
            this.computeSequenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpComputeScalarDefinedValues
{

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpComputeScalarDefinedValuesDefinedValue definedValueField;

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpComputeScalarDefinedValuesDefinedValue DefinedValue
    {
        get
        {
            return this.definedValueField;
        }
        set
        {
            this.definedValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpComputeScalarDefinedValuesDefinedValue
{

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpComputeScalarDefinedValuesDefinedValueColumnReference columnReferenceField;

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpComputeScalarDefinedValuesDefinedValueScalarOperator scalarOperatorField;

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpComputeScalarDefinedValuesDefinedValueColumnReference ColumnReference
    {
        get
        {
            return this.columnReferenceField;
        }
        set
        {
            this.columnReferenceField = value;
        }
    }

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpComputeScalarDefinedValuesDefinedValueScalarOperator ScalarOperator
    {
        get
        {
            return this.scalarOperatorField;
        }
        set
        {
            this.scalarOperatorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpComputeScalarDefinedValuesDefinedValueColumnReference
{

    private string columnField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Column
    {
        get
        {
            return this.columnField;
        }
        set
        {
            this.columnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpComputeScalarDefinedValuesDefinedValueScalarOperator
{

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpComputeScalarDefinedValuesDefinedValueScalarOperatorIntrinsic intrinsicField;

    private string scalarStringField;

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpComputeScalarDefinedValuesDefinedValueScalarOperatorIntrinsic Intrinsic
    {
        get
        {
            return this.intrinsicField;
        }
        set
        {
            this.intrinsicField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ScalarString
    {
        get
        {
            return this.scalarStringField;
        }
        set
        {
            this.scalarStringField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpComputeScalarDefinedValuesDefinedValueScalarOperatorIntrinsic
{

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpComputeScalarDefinedValuesDefinedValueScalarOperatorIntrinsicScalarOperator[] scalarOperatorField;

    private string functionNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ScalarOperator")]
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpComputeScalarDefinedValuesDefinedValueScalarOperatorIntrinsicScalarOperator[] ScalarOperator
    {
        get
        {
            return this.scalarOperatorField;
        }
        set
        {
            this.scalarOperatorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FunctionName
    {
        get
        {
            return this.functionNameField;
        }
        set
        {
            this.functionNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpComputeScalarDefinedValuesDefinedValueScalarOperatorIntrinsicScalarOperator
{

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpComputeScalarDefinedValuesDefinedValueScalarOperatorIntrinsicScalarOperatorConst constField;

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpComputeScalarDefinedValuesDefinedValueScalarOperatorIntrinsicScalarOperatorConst Const
    {
        get
        {
            return this.constField;
        }
        set
        {
            this.constField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpComputeScalarDefinedValuesDefinedValueScalarOperatorIntrinsicScalarOperatorConst
{

    private string constValueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ConstValue
    {
        get
        {
            return this.constValueField;
        }
        set
        {
            this.constValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanRelOpUpdateRelOpComputeScalarRelOpComputeScalarRelOp
{

    private object outputListField;

    private object constantScanField;

    private byte nodeIdField;

    private string physicalOpField;

    private string logicalOpField;

    private byte estimateRowsField;

    private byte estimateIOField;

    private float estimateCPUField;

    private byte avgRowSizeField;

    private float estimatedTotalSubtreeCostField;

    private byte parallelField;

    private byte estimateRebindsField;

    private byte estimateRewindsField;

    private string estimatedExecutionModeField;

    /// <remarks/>
    public object OutputList
    {
        get
        {
            return this.outputListField;
        }
        set
        {
            this.outputListField = value;
        }
    }

    /// <remarks/>
    public object ConstantScan
    {
        get
        {
            return this.constantScanField;
        }
        set
        {
            this.constantScanField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte NodeId
    {
        get
        {
            return this.nodeIdField;
        }
        set
        {
            this.nodeIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PhysicalOp
    {
        get
        {
            return this.physicalOpField;
        }
        set
        {
            this.physicalOpField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LogicalOp
    {
        get
        {
            return this.logicalOpField;
        }
        set
        {
            this.logicalOpField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte EstimateRows
    {
        get
        {
            return this.estimateRowsField;
        }
        set
        {
            this.estimateRowsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte EstimateIO
    {
        get
        {
            return this.estimateIOField;
        }
        set
        {
            this.estimateIOField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float EstimateCPU
    {
        get
        {
            return this.estimateCPUField;
        }
        set
        {
            this.estimateCPUField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte AvgRowSize
    {
        get
        {
            return this.avgRowSizeField;
        }
        set
        {
            this.avgRowSizeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float EstimatedTotalSubtreeCost
    {
        get
        {
            return this.estimatedTotalSubtreeCostField;
        }
        set
        {
            this.estimatedTotalSubtreeCostField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte Parallel
    {
        get
        {
            return this.parallelField;
        }
        set
        {
            this.parallelField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte EstimateRebinds
    {
        get
        {
            return this.estimateRebindsField;
        }
        set
        {
            this.estimateRebindsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte EstimateRewinds
    {
        get
        {
            return this.estimateRewindsField;
        }
        set
        {
            this.estimateRewindsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EstimatedExecutionMode
    {
        get
        {
            return this.estimatedExecutionModeField;
        }
        set
        {
            this.estimatedExecutionModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanParameterList
{

    private ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanParameterListColumnReference columnReferenceField;

    /// <remarks/>
    public ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanParameterListColumnReference ColumnReference
    {
        get
        {
            return this.columnReferenceField;
        }
        set
        {
            this.columnReferenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
public partial class ShowPlanXMLBatchSequenceBatchStmtSimpleQueryPlanParameterListColumnReference
{

    private string columnField;

    private string parameterDataTypeField;

    private string parameterCompiledValueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Column
    {
        get
        {
            return this.columnField;
        }
        set
        {
            this.columnField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ParameterDataType
    {
        get
        {
            return this.parameterDataTypeField;
        }
        set
        {
            this.parameterDataTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ParameterCompiledValue
    {
        get
        {
            return this.parameterCompiledValueField;
        }
        set
        {
            this.parameterCompiledValueField = value;
        }
    }
}
